version: "3"
services:
  functions:
    build: .
    ports:
    - "8080:80"
    depends_on:
    - mongo
    environment:
    - MongoDbConnection=mongodb://mongo:27017
    - MongoDbDatabase=ToDos
    - MongoDbCollection=MyToDos

    - AzureSignalRConnectionString=Endpoint=https://mytodos.service.signalr.net;AccessKey=a5gTwSTLiRKQcPXkG/iGnE+JLo7Huvyi8GFiEE7a0x8=;Version=1.0;
    #env_file:
    #- web-variables.env
  mongo:
    image: mongo:4.0.4
    ports:
    - "27017:27017"